#!/usr/bin/env python3
"""Copy the regenerated tables and figures to manuscript_artifacts/ under the manuscript's labels.

manuscript_artifacts/tables/  <- results/tables/*.csv|.tex
manuscript_artifacts/figures/ <- results/figures/*.pdf|.png
manuscript_artifacts/INDEX.md lists which manuscript table/figure each file corresponds to.
Files are overwritten with the newly generated version (they are build products, not raw data).
"""
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "common"))
import repo  # noqa: E402

ART = os.path.join(repo.ROOT, "manuscript_artifacts")
TABLES = [("table_cycles", "Table III (per-phase evaluation of Eq. 3)"), ("table_verification", "Table IV (verification coverage)"),
          ("table_resources", "Table V (per-phase reference vs shared-PE)"), ("table_pipelined", "Table VI (primary vs pipelined Barrett)"),
          ("table_hierarchy", "Table VIII (per-module attribution)"), ("table_security", "countermeasure table / TVLA summary")]
FIGS = [("fig_cycle_breakdown", "Fig. 10(a) clock-cycle budget"), ("fig_area_breakdown", "Fig. 10(b) LUT attribution"),
        ("fig_critical_path", "Fig. 11(a) critical-path delay"), ("fig_power", "Fig. 11(b) on-chip power"),
        ("fig_slack_distribution", "Fig. 12 cumulative slack distribution"), ("fig_tvla", "TVLA figure (shared-PE vs per-phase)"),
        ("fig_countermeasures", "countermeasure TVLA traces")]


def main():
    lines = ["# Manuscript artifacts", "", "Regenerated by `./reproduce_all.sh` (stage 11). Table VII (published designs of other authors) is external data and is not regenerated.", "",
             "| File(s) | Manuscript item |", "|---|---|"]
    n = 0
    for sub, src, items, exts in (("tables", repo.TABLE_DIR, TABLES, ("csv", "tex")), ("figures", repo.FIG_DIR, FIGS, ("pdf", "png"))):
        os.makedirs(os.path.join(ART, sub), exist_ok=True)
        for stem, label in items:
            got = []
            for e in exts:
                p = os.path.join(src, f"{stem}.{e}")
                if os.path.exists(p):
                    shutil.copy(p, os.path.join(ART, sub, f"{stem}.{e}"))
                    got.append(e)
                    n += 1
            lines.append(f"| `{sub}/{stem}.{{{','.join(got)}}}` | {label} |" if got else f"| `{sub}/{stem}` | {label} -- not generated |")
    with open(os.path.join(ART, "INDEX.md"), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"[artifacts] copied {n} files to manuscript_artifacts/")


if __name__ == "__main__":
    main()
