#!/usr/bin/env python3
"""Format the manuscript tables (CSV + LaTeX) from the machine-readable results.

Every number is read from the same JSON/CSV files the consistency checker uses
(results/json/derived_metrics.json, vivado_results.json, cycle_counts.csv, tvla_summary.json,
functional/barrett/ct/masking/shuffling JSON). Values are unrounded in those files and are
rounded here, once, with the precision the manuscript prints.

Outputs (results/tables/)
  table_cycles.{csv,tex}        manuscript Table III  (per-phase evaluation of Eq. 3)
  table_verification.{csv,tex}  Table IV              (verification coverage)
  table_resources.{csv,tex}     Table V               (per-phase reference vs shared-PE)
  table_pipelined.{csv,tex}     Table VI              (primary vs pipelined Barrett)
  table_hierarchy.{csv,tex}     Table VIII            (per-module LUT / DSP attribution)
  table_security.{csv,tex}      countermeasure table + unprotected TVLA summary
Table VII (published designs of other authors) is external data and is not regenerated.
A cell whose source value is unavailable prints SKIPPED.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "common"))
import repo  # noqa: E402

NA = "SKIPPED"


def j(name):
    p = os.path.join(repo.JSON_DIR, name)
    return repo.read_json(p) if os.path.exists(p) else None


def f(v, nd=1, thousands=False, sign=False):
    if v is None:
        return NA
    if isinstance(v, str):
        return v
    s = f"{v:,.{nd}f}" if thousands else f"{v:.{nd}f}"
    if sign and v > 0:
        s = "+" + s
    return s


def pct(v, nd=1):
    return NA if v is None else (f"{v:+.{nd}f}\\%".replace("+-", "-"))


def tex_escape_pct(s):
    return s


def write_table(name, header, rows, caption_note):
    repo.write_csv(os.path.join(repo.TABLE_DIR, f"{name}.csv"), header, rows)
    cols = "l" + "r" * (len(header) - 1)
    lines = [f"% generated by scripts/reporting/format_tables.py -- {caption_note}",
             "\\begin{tabular}{@{}" + cols + "@{}}", "\\toprule", " & ".join(header) + " \\\\", "\\midrule"]
    for r in rows:
        if len(r) == 1 or (r[1:] == [""] * (len(r) - 1)):
            lines.append("\\multicolumn{" + str(len(header)) + "}{@{}l}{\\textit{" + str(r[0]) + "}} \\\\")
        else:
            lines.append(" & ".join(str(c).replace("%", "\\%").replace("\\\\%", "\\%").replace("_", "\\_") for c in r) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    with open(os.path.join(repo.TABLE_DIR, f"{name}.tex"), "w") as fh:
        fh.write("\n".join(lines))
    print(f"[tables] wrote results/tables/{name}.csv and .tex")


def cycles_table():
    path = os.path.join(repo.CSV_DIR, "cycle_counts.csv")
    if not os.path.exists(path):
        return
    rows = repo.read_csv(path)
    by = {(r["design"], r["phase"]): r for r in rows}
    out = []
    for phase in ("Forward NTT (x2)", "Pointwise multiplication", "Inverse NTT", "Final scaling", "Phase init/done", "TOTAL"):
        p, q = by[("shared_pe", phase)], by[("pipelined_barrett", phase)]
        out.append([phase.replace("TOTAL", "Total"), p["runs"], p["states_per_run"], p["wait_states_per_run"], p["multiplier_issues"],
                    f(int(p["rtl_cycles"]), 0, True) if p["rtl_cycles"].isdigit() else NA,
                    f(int(q["rtl_cycles"]), 0, True) if q["rtl_cycles"].isdigit() else NA])
    write_table("table_cycles", ["Phase", "Runs", "St.", "Wt.", "Iss.", "c=3 (cycles)", "c=4 (cycles)"], out,
                "Table III; cycle columns are RTL-simulation counts")


def verification_table():
    fv, bv = j("functional_verification.json"), j("barrett_verification.json")
    cs = {d: j(f"sim_constant_time_{k}.json") for d, k in (("shared_pe", "shared"), ("pipelined_barrett", "pipelined"))}
    rows = []
    if bv:
        rtl = bv.get("rtl_simulation", {})
        rows.append(["Barrett reduction", "x mod q", f"all {bv['tested_inputs']:,} inputs",
                     f"{bv['mismatches']} mism. (model); RTL {rtl.get('status', NA)}"])
    if fv:
        sp = fv["rtl"].get("shared_pe", {})
        rows.append(["Polynomial product", "schoolbook multiplication", f"{f(sp.get('coefficients_checked'), 0, True)} coeff.",
                     f"{sp.get('mismatches', NA)} mism."])
        rows.append(["Known-answer identities", "derived by hand", "4 identities",
                     "all hold" if all(v == "PASS" for v in fv["known_answer_identities"].values()) else "FAIL"])
    if all(cs.values()):
        ok = all(c.get("pass") for c in cs.values())
        rows.append(["Control trajectory", "reference trace (vector 0)", f"{cs['shared_pe']['vectors']} vec., 2 designs",
                     "identical" if ok else "DIFFERS"])
    write_table("table_verification", ["Component", "Reference", "Test space", "Result"], rows, "Table IV")


def resources_tables():
    dm = j("derived_metrics.json")
    if not dm:
        return
    D, C = dm["designs"], dm["changes"].get("shared_vs_per_phase", {})
    if "shared_pe" not in D or "per_phase_baseline" not in D:
        return
    b, s = D["per_phase_baseline"], D["shared_pe"]
    hb, hs = dm["hierarchy"]["per_phase_baseline"], dm["hierarchy"]["shared_pe"]

    def row(label, key, nd=0, th=False, chg=True):
        return [label, f(b.get(key), nd, th), f(s.get(key), nd, th), pct(C.get(key)) if chg else "--"]
    rows = [["Resource utilization (xc7a35t)", "", "", ""],
            row("Occupied slices", "slices"), row("Slice LUTs (total)", "luts"), row("LUT as logic", "lut_logic"),
            ["LUT as memory", f(b["lut_memory"], 0), f(s["lut_memory"], 0), "--"],
            row("Slice registers (FF)", "ffs"), row("DSP48E1 blocks", "dsp"),
            ["BRAM (36Kb)", f(b["bram36"], 0), f(s["bram36"], 0), "--"],
            row("LUT utilisation (%)", "lut_util_pct", 1, chg=False), row("DSP utilisation (%)", "dsp_util_pct", 1, chg=False),
            ["Datapath composition", "", "", ""],
            ["Modular multipliers", hb["Multiplier(s)"]["instances"], hs["Multiplier(s)"]["instances"],
             pct((hs["Multiplier(s)"]["instances"] / hb["Multiplier(s)"]["instances"] - 1) * 100)],
            ["Modular ADD/SUB units", hb["Adder(s)"]["instances"] + hb["Subtractor(s)"]["instances"],
             hs["Adder(s)"]["instances"] + hs["Subtractor(s)"]["instances"],
             pct(((hs["Adder(s)"]["instances"] + hs["Subtractor(s)"]["instances"]) /
                  (hb["Adder(s)"]["instances"] + hb["Subtractor(s)"]["instances"]) - 1) * 100)],
            ["DSP per multiplier", f(b["dsp"] / hb["Multiplier(s)"]["instances"], 0), f(s["dsp"] / hs["Multiplier(s)"]["instances"], 0), "--"],
            ["Timing and performance", "", "", ""],
            row("Fmax derived (MHz)", "fmax_derived_mhz", 1), row("Fmax closed (MHz)", "fmax_closed_mhz", 1),
            row("Clock period (ns)", "closed_period_ns", 3),
            ["Clock cycles / poly mult", f(b.get("cycles"), 0, True), f(s.get("cycles"), 0, True), "--"],
            row("Latency (us)", "latency_us", 1), row("Throughput (poly mult/s)", "throughput_per_s", 0),
            ["Power (post route, vectorless, 10 ns)", "", "", ""],
            row("Dynamic power (mW)", "dynamic_mw", 2), ["Static power (mW)", f(b.get("static_mw"), 1), f(s.get("static_mw"), 1), "--"],
            row("Total power (mW)", "total_mw", 1),
            ["Efficiency figures of merit", "", "", ""],
            row("Energy / op (uJ)", "energy_per_op_uj", 2), row("ATP (LUT.us)", "atp_lut_us", 0, True),
            row("DTP (DSP.us)", "dtp_dsp_us", 0, True), row("EDP (nJ.s)", "edp_nj_s", 2)]
    write_table("table_resources", ["Metric", "Per-phase reference", "Shared-PE", "Change"], rows, "Table V")

    if "pipelined_barrett" in D:
        p, pc = D["pipelined_barrett"], dm["changes"].get("pipelined_vs_primary", {})
        rows6 = [["LUTs", f(s["luts"], 0), f(p["luts"], 0), pct(pc.get("luts"))],
                 ["FFs", f(s["ffs"], 0), f(p["ffs"], 0), pct(pc.get("ffs"))],
                 ["DSP48E1", f(s["dsp"], 0), f(p["dsp"], 0), "--"],
                 ["Multiply-reduce latency", "2 cyc.", "3 cyc.", "+1 cyc."],
                 ["Clock cycles / poly mult", f(s.get("cycles"), 0, True), f(p.get("cycles"), 0, True), pct(pc.get("cycles"))],
                 ["Closed period (ns)", f(s.get("closed_period_ns"), 3), f(p.get("closed_period_ns"), 3), pct(pc.get("closed_period_ns"))],
                 ["Fmax closed (MHz)", f(s.get("fmax_closed_mhz"), 1), f(p.get("fmax_closed_mhz"), 1), f(pc.get("fmax_ratio"), 2) + "x"],
                 ["Latency (us)", f(s.get("latency_us"), 1), f(p.get("latency_us"), 1), pct(pc.get("latency_us"))]]
        write_table("table_pipelined", ["Metric", "Primary", "Pipelined", "Change"], rows6, "Table VI")

    rows8 = []
    for g in ("Control + storage", "Multiplier(s)", "Adder(s)", "Subtractor(s)"):
        rows8.append([g, hb[g]["luts"], hb[g]["dsp"], hs[g]["luts"], hs[g]["dsp"]])
    rows8.append(["Instances (MUL/ADD/SUB)", f"{hb['Multiplier(s)']['instances']} / {hb['Adder(s)']['instances']} / {hb['Subtractor(s)']['instances']}", "",
                  f"{hs['Multiplier(s)']['instances']} / {hs['Adder(s)']['instances']} / {hs['Subtractor(s)']['instances']}", ""])
    write_table("table_hierarchy", ["Module group", "Per-phase LUT", "Per-phase DSP", "Shared-PE LUT", "Shared-PE DSP"], rows8, "Table VIII")


def security_table():
    tv = j("tvla_summary.json")
    if not tv:
        return
    e = tv["experiments"]
    sh = j("shuffling_verification.json") or {}
    mk = j("masking_verification.json") or {}
    rows = []

    def add(label, key, lat, hw):
        if key in e:
            x = e[key]
            rows.append([label, f(x["max_abs_t"], 2 if key == "masked" else 1), f"{x['n_above_threshold']} / {x['cycles_evaluated']:,}",
                         f(x["expected_false_positives"], 2), lat, hw])
    add("Unprotected (shared-PE)", "main_shared", "1.00x", "--")
    add("Unprotected (per-phase reference)", "main_baseline", "1.00x", "--")
    add("Matched control for shuffling", "shuffle_off", "1.00x", "--")
    ff = (sh.get("added_state") or {}).get("total_flip_flops")
    add("Shuffled order", "shuffle_on", "1.00x", f"{ff} FF (declared)" if ff else NA)
    ratio = (mk.get("rtl") or {}).get("latency_ratio") or (mk.get("latency") or {}).get("ratio")
    add("Masked, two runs", "masked", f"{ratio:.2f}x" if ratio else NA, "none")
    write_table("table_security", ["Configuration", "max|t|", "Leakage (|t|>4.5)", "Chance", "Latency", "Hardware"], rows,
                "countermeasure table; 400 traces/group, simulated register-level Hamming-distance model")


def main():
    repo.ensure(repo.TABLE_DIR)
    cycles_table()
    verification_table()
    resources_tables()
    security_table()


if __name__ == "__main__":
    main()
